package media

import (
	"context"
	"io"
	"time"
)

// UploadIntent is server-created and belongs to the authenticated account.
// ObjectKey is opaque; callers must not derive it from a filename or account ID.
type UploadIntent struct {
	ID        string
	OwnerID   string
	ObjectKey string
	MIMEType  string
	MaxBytes  int64
	SHA256Hex string
	ExpiresAt time.Time
}

type UploadTarget struct {
	URL       string
	Headers   map[string]string
	ExpiresAt time.Time
}

type ObjectInfo struct {
	ByteSize int64
}

// Storage separates untrusted quarantine objects from private originals and
// approved public derivatives. Every key is generated by Birdtie.
type Storage interface {
	SignQuarantineWrite(context.Context, UploadIntent) (UploadTarget, error)
	OpenQuarantine(context.Context, string) (io.ReadCloser, ObjectInfo, error)
	PutPrivate(context.Context, string, io.Reader) error
	PutPublicDerivative(context.Context, string, io.Reader) error
	DeleteQuarantine(context.Context, string) error
	DeletePrivate(context.Context, string) error
	DeletePublicDerivative(context.Context, string) error
}

type ScanVerdict string

const (
	ScanClean    ScanVerdict = "clean"
	ScanRejected ScanVerdict = "rejected"
)

// A scanner error is not a clean verdict. The caller must fail closed.
type Scanner interface {
	Scan(context.Context, io.Reader) (ScanVerdict, error)
}

// PrivateMetadata may contain precise location. It must be encrypted before
// persistence and never serialized into a public City Graph response.
type PrivateMetadata struct {
	CapturedAt *time.Time
	RawEXIF    []byte
	Latitude   *float64
	Longitude  *float64
}

type MetadataExtractor interface {
	Extract(context.Context, io.Reader) (PrivateMetadata, error)
}

// DerivativeBuilder applies orientation and re-encodes verified image content.
// Its output must not contain EXIF, GPS or other sensitive metadata.
type DerivativeBuilder interface {
	BuildPublic(context.Context, io.Reader, string) (io.ReadCloser, string, error)
}
